Add more guest functionality added to the template
amakarudze/bnb pull request #26
Opened 2024-10-14 10:39 UTC by meenakshiAS

I have created a new folder (js) in the static forlder.
The "js" folder has file name called "add_guests.js" that contains the javascript code for add more guest functionality
Also made some changes in the "reservation.html" file

2024-10-15 19:48 UTC, amakarudze requested changes
Hey @meenakshiAS. Thanks for your work on this. May you kindly address the changes I have suggested. Thanks. Also update your test and fixtures accordingly.

2024-10-15 19:48 UTC, amakarudze commented on reservations/views.py
> +    return render(request, "website/reservation_success.html")
```suggestion

```
This is not necessary remove it.

2024-10-15 19:48 UTC, amakarudze commented on reservations/urls.py
> +    path('sign-up-for-guest/', views.staff_sign_up_for_guest, name='sign-up-for-guest'),
```suggestion
   
```

Let's delete this and go with one view.

2024-10-15 19:48 UTC, amakarudze commented on reservations/urls.py
> +from .views import staff_sign_up_for_guest, make_reservation
```suggestion

```
You are importing views twice, not necessary and not good at all.

2024-10-15 19:48 UTC, amakarudze commented on reservations/views.py
> +def staff_sign_up_for_guest(request):
```suggestion
def add_reservation(request):

```
Let's rename this view so it makes sense.

2024-10-15 19:48 UTC, amakarudze commented on reservations/views.py
> +    return render(request, "website/reservation_success.html")
```suggestion
    form = StaffReservationForm()
    if request.method == "POST":
        form = AddReservationForm(request.POST)
        guest_formset = GuestFormSet(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                email=form.cleaned_data.get("email"),
                first_name=form.cleaned_data.get("first_name"),
                last_name=form.cleaned_data.get("last_name"),
                password=form.cleaned_data.get("password"),
            )
            UserProfile.objects.create(
            user=user,
            dob=form.cleaned_data.get("dob"),
            address=form.cleaned_data.get("address"),
            city=form.cleaned_data.get("city"),
            postal_code=form.cleaned_data.get("postal_code"),
            state=form.cleaned_data.get("state"),
            country=form.cleaned_data.get("country"),
            phone_number=form.cleaned_data.get("phone_number"),
            )
            reservation = Reservation.objects.create(
            user=user,
            number_of_adults=form.cleaned_data.get("number_of_adults")
            number_of_children=form.cleaned_data.get("number_of_children")
            rooms=form.cleaned_data.get("rooms")
            events=form.cleaned_data.get("event")
            check_in_date=form.cleaned_data.get("check_in_date")
            check_out_date=form.cleaned_data.get("check_out_date")
              )
        if guest_formset.is_valid():
             for guest_form in guest_formset:
                if guest_form.cleaned_data:  
                    guest = guest_form.save(commit=False)
                    guest.reservation = reservation
                    guest.save()

            messages.success(request, "New reservation added successfully")
            return redirect("reservations:reservations_list")
        
    else:
        form = AddReservationForm()

    return render(request, "reservations/reservation.html", {"form": form, "guest_formset": guest_formset})

```

Let's go with one view like this.

2024-10-15 22:10 UTC, meenakshiAS commented
> Hey @meenakshiAS. Thanks for your work on this. May you kindly address the changes I have suggested. Thanks. Also update your test and fixtures accordingly.

ok

2024-10-20 10:48 UTC, amakarudze commented
Closing this one again to avoid confusion.

2024-10-20 10:48 UTC, closed without merging